local L = LibStub("AceLocale-3.0"):NewLocale("HonorSpy", "esES")

if L then

L["HonorSpy Standings"] = "Clasificación de HonorSpy"
L["Name"] = "Nombre"
L["Honor"] = "Honor"
L["ThisWeekHonor"] = "Esta semana"
L["EstHonor"] = "HonorEst."
L["LstWkHonor"] = "Previa semana"
L["Standing"] = "Clasificación"
L["RP"] = "JR"
L["Rank"] = "Rango"
L["LastSeen"] = "Última vez visto"
L["Progress of"] = "Progreso de"
L["d"] = "d"
L["h"] = "h"
L["m"] = "m"
L["s"] = "s"

L["Weekly data was reset"] = "Se restablecieron los datos semanales"
L["This will purge ALL addon data, you sure?"] = "Esto purgará TODOS los datos del addon, ¿estás seguro?"
L["All data was purged"] = "Todos los datos fueron purgados"
L["Show HonorSpy Standings"] = "Mostrar clasificación HonorSpy"
L["Report specific player standings"] = "Informar la clasificación de jugadores específicos"
L["player_name"] = "nombre_jugador"
L["Player %s not found in table"] = "No se encuentra el jugador %s en la tabla"

L["Pool Booster Count"] = "Recuento de potenciadores de grupo"
L["Number of characters to add to Pool"] = "Número de jugadores para agregar al grupo"

L["Report"] = "Informar"
L["Report for player"] = "Informa para jugador"
L["Report Target"] = "Informa objetivo"
L["Report Me"] = "Informame"
L["Pool Size"] = "Tamaño del grupo"
L["Natural Pool Size"] = "Tamaño del grupo natural"
L["Boosted Pool Size"] = "Tamaño del grupo aumentado"
L["Standing"] = "Clasificación"
L["Bracket"] = "Grupo"
L["Current RP"] = "JR actual"
L["Next Week RP"] = "JR próxima semana"
L["Current Rank"] = "Rango actual"
L["Next Week Rank"] = "Rango próxima semana"
L["HonorSpy Options"] = "Opciones de HonorSpy"
L["Sunday"] = "Domingo"
L["Monday"] = "Lunes"
L["Tuesday"] = "Martes"
L["Wednesday"] = "Miércoles"
L["Thursday"] = "Jueves"
L["Friday"] = "Viernes"
L["Saturday"] = "Sábado"
L["PvP Week Reset On"] = "Reinicio en"
L["Day of week when new PvP week starts (10AM UTC)"] = "Día de la semana en el que comienza la nueva semana JcJ (10:00 a.m. UTC)"
L["Sort By"] = "Ordenar por"
L["Set up sorting column"] = "Configurar columna de orden"
L["Export to CSV"] = "Exportar a CSV"
L["Show window with current data in CSV format"] = "Mostrar ventana con datos actuales en formato CSV"
L["Report My Standing"] = "Informar mi clasificación"
L["Reports your current standing as emote"] = "Informa tu clasificación actual como gesto"
L["_ purge all data"] = "_ purgar todos los datos"
L["Delete all collected data"] = "Eliminar todos los datos recopilados"
L["Limit Rows"] = "Limitar filas"
L["Limits number of rows shown in table, from 1 to 9999"] = "Limita el número de filas que se muestran en la tabla, de 1 a 9999"
L["<EP>"] = "<EP>"
L["Limit"] = "Límite"
L['You have 0 honor or not enough HKs, min = 15'] = "Tienes 0 honor o no tienes suficientes muertes con honor, min = 15"
L["Hide Minimap Button"] = "Ocultar botón de minimapa"
L["Use \'/hs show\' to bring HonorSpy window, if hidden. Will Reload UI on change."] = "Usar \'/hs show\' para mostrar la ventana HonorSpy si está oculto. Recargará la interfaz de usuario al cambiar."
L["Show Estimated Honor"] = "Mostrar honor estimado"
L["Shows the Estimated Honor column in the table. This data will only be populated by other people with HonorSpy."] = true
L["Estimated Honor"] = "Honor estimado"
L["Sync over GUILD instead of separate 'HonorSpySync' channel"] = "Sincroniza a través de HERMANDAD en lugar de un canal 'HonorSpySync' separado"
L["You won't join 'HonorSpySync' channel anymore and will only sync data with your guildmates. Relog after changing this."] = "Ya no te unirás al canal 'HonorSpySync' y solo sincronizarás datos con tus compañeros de hermandad. Conecta de nuevo después de cambiar esto."
L["This is how big the discrepancy is at the end of PvP week between HonorSpy pool size and real server pool size. Pool size will slowly be growing during the week reaching the final value of 'gathered number of players' + 'pool boost size'."] = "Así de grande es la discrepancia al final de la semana de JcJ entre el tamaño del grupo de HonorSpy y el tamaño real del grupo de servidores. El tamaño del grupo crecerá lentamente durante la semana alcanzando el valor final de 'número de jugadores reunidos' + 'tamaño de aumento del grupo'."

end
