local L = LibStub("AceLocale-3.0"):NewLocale("HonorSpy", "zhCN") -- translate by Qcat

if L then

L["HonorSpy Standings"] = "荣誉监视榜"
L["Name"] = "名字"
L["Honor"] = "荣誉"
L["ThisWeekHonor"] = "本周荣誉"
L["LstWkHonor"] = "上周荣誉"
L["Standing"] = "排名表"
L["RP"] = "经验"
L["Rank"] = "Rank"
L["LastSeen"] = "最近发现"
L["Progress of"] = "角色进展 - "
L["d"] = "天"
L["h"] = "小时"
L["m"] = "分"
L["s"] = "秒"

L["Weekly data was reset"] = "每周数据被重置"
L["This will purge ALL addon data, you sure?"] = "这将清除所有插件数据，你确定吗？"
L["All data was purged"] = "所有数据被清除"
L["Show HonorSpy Standings"] = "显示荣誉监视榜"
L["Report specific player standings"] = "报告指定玩家排名"
L["player_name"] = "玩家名字"
L["Player %s not found in table"] = "玩家%s未在表单里"

L["Report"] = "报告"
L["Report for player"] = "报告玩家"
L["Report Target"] = "报告目标"
L["Report Me"] = "报告自己"
L["Pool Size"] = "数据表的大小"
L["Standing"] = "排名"
L["Bracket"] = "Br等级段"
L["Current RP"] = "当前经验"
L["Next Week RP"] = "下周经验"
L["Current Rank"] = "当前Rank"
L["Next Week Rank"] = "下周Rank"
L["HonorSpy Options"] = "HonorSpy 荣誉监视榜选项"
L["Sunday"] = "星期日"
L["Monday"] = "星期一"
L["Tuesday"] = "星期二"
L["Wednesday"] = "星期三"
L["Thursday"] = "星期四"
L["Friday"] = "星期五"
L["Saturday"] = "星期六"
L["PvP Week Reset On"] = "PvP刷新重置"
L["Day of week when new PvP week starts (10AM UTC)"] = "新PVP周开始的日子(默认早上10点)"
L["Sort By"] = "排列方式"
L["Set up sorting column"] = "设置列排序方式"
L["Export to CSV"] = "导出到CSV文件"
L["Show window with current data in CSV format"] = "显示CSV格式的当前数据的窗口"
L["Report My Standing"] = "报告我的排名"
L["Reports your current standing as emote"] = "用表情报告你当前的排名状态"
L["_ purge all data"] = "清除所有数据"
L["Delete all collected data"] = "删除所有收集的数据"
L["Limit Rows"] = "行数限制"
L["Limits number of rows shown in table, from 1 to 9999"] = "限制表中显示的行数，从1到9999"
L["<EP>"] = "<EP>"
L["Limit"] = "限制"
L['You have 0 honor or not enough HKs, min = 15'] = "您有0荣誉或没有荣誉击杀, 最低需要 = 15"
L["Hide Minimap Button"] = "隐藏小地图按钮"
L["Use \'/hs show\' to bring HonorSpy window, if hidden. Will Reload UI on change."] = "输入 \'/hs show' 显示 HonorSpy 窗口, 更改时将重置UI"
L["Estimated Honor"] = "荣誉预估"
L["Sync over GUILD instead of separate 'HonorSpySync' channel"] = "通过公会同步而不是单独的“HonorSpySync”频道"
L["You won't join 'HonorSpySync' channel anymore and will only sync data with your guildmates. Relog after changing this."] = "你将不再加入‘HonorSpySync’频道，并且只与你的公会成员同步数据。更改后请重载登陆"

end
