local L = AceLibrary("AceLocale-2.2"):new("HonorSpy")

L:RegisterTranslations("enUS", function() return {
	["HonorSpy standings"] = true,
	["Name"] = true,
	["ThisWeekHonor"] = true,
	["LastWeekHonor"] = true,
	["Standing"] = true,
	["RP"] = true,
	["Rank"] = true,
	["d"] = true,
	["h"] = true,
	["m"] = true,
	["s"] = true,
	
	["Weekly data was reset"] = true,
	["This will purge ALL addon data, you sure?"] = true,
	["All data was purged"] = true,
	["Show HonorSpy Standings"] = true,
	["Report specific player standings"] = true,
	["player_name"] = true,
	["Player %s not found in table"] = true,
	
	["Report for player"] = true,
	["Pool Size"] = true,
	["Standing"] = true,
	["Bracket"] = true,
	["current RP"] = true,
	["Next Week RP"] = true,
	["Current Rank"] = true,
	["Next Week Rank"] = true,
	["HonorSpy options"] = true,
	["Sunday"] = true,
	["Monday"] = true,
	["Tuesday"] = true,
	["Wednesday"] = true,
	["Thursday"] = true,
	["Friday"] = true,
	["Saturday"] = true,
	["PvP Week Reset On"] = true,
	["Day of week when new PvP week starts (10AM UTC)"] = true,
	["Sort By"] = true,
	["Set up sorting column"] = true,
	["Export to CSV"] = true,
	["Show window with current data in CSV format"] = true,
	["Report My Standing"] = true,
	["Reports your current standing as emote"] = true,
	["_ purge all data"] = true,
	["Delete all collected data"] = true,
	["Limit Rows"] = true,
	["Limits number of rows shown in table"] = true,
	["<EP>"] = true,
	["Limit"] = true,
} end)